Feature/t48056
rich-id/terms-module pull request #1
Opened 2021-07-16 10:06 UTC by hdumazeau

2021-07-19 09:03 UTC, NicolasGuilloux requested changes

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Entity/TermsVersion.php
> +
ligne en trop

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Entity/TermsVersion.php
> +    public static function buildDefaultVersion(Terms $terms): self
Mettre dans une Factory et Updater

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Entity/TermsVersion.php
> +
ligne en trop

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Entity/TermsVersion.php
> +        $entity->setTitle($termsVersion->getTitle()); /* @phpstan-ignore-line */
Je suis pas fan du PHPStan Ignore, un if avec un throw résoudrait ça

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Entity/TermsVersion.php
> +    public function update(TermsEdition $termsEdition): self
Updater

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Entity/TermsVersionSignature.php
> +    public static function sign(TermsVersion $version, TermsSubjectInterface $subject): self
Factory

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Exception/AlreadyEnabledTermsVersionException.php
> +            \sprintf('Version %d of terms %s is already enabled.', $termsVersion->getVersion(), $terms->getSlug())
Tu peux faire une variable message ? Et mettre l'appel au parent à la fin

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Exception/CannotAddVersionToTermsException.php
> +            \sprintf('Cannot add new version to the terms %s.', $terms->getSlug())
dans une variable message (pareil poru toutes les exceptions)

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Exception/TermsModuleException.php
> +class TermsModuleException extends \Exception
Si elle est utilisée quelque part, mets un message par défaut, sinon mets le abstract

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Fetcher/GetTermsVersionToSign.php
> +        if ($terms === null) {
Tu peux faire une fonction protected `check` qui throw les exception au besoin

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Model/DummySubject.php
> +    public function __construct()
Alors mets le private :p

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Model/DummySubject.php
> +
ligne en trop

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Model/DummyTermsGuardValidation.php
> +    public function __construct()
private

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Model/DummyTermsGuardValidation.php
> +    public static function create(string $slug, string $type, string $identifier): self
Factory

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Model/TermsEdition.php
> +use RichId\TermsModuleBundle\Infrastructure\ValidatorConstraints;
as Constraints

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Model/TermsEdition.php
> +
Nouvelle ligne

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/Port/EntityRecoderInterface.php
> +    public function flush(): void;
Flush ça expose trop le fonctionnement de ton infra

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/UseCase/ActivateTermsVersion.php
> +            new TermsVersionEnabledEvent($termsVersion)
A la limite, tu pourrais faire un EventDispatcher qui se charge d'instancier l'event pour toi, ou alors tu peux choisir de faire une fonction générique qui accepte une classe abstract TermsEvent

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/UseCase/CreateTermsVersion.php
> +        $this->entityRecoder->flush();
Soit saveTermsVersion flush tout le temps, soit c'est fait en dehors du UseCase

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Domain/UseCase/SignTerms.php
> +            $this->entityRecoder->flush();
J'aime pas

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Infrastructure/Adapter/EntityRecorder.php
> +    public function flush(): void
Non du coup, soit tu flush tout le temps (ce qui n'est pas horrible en soit), soit tu précises dans la doc que les entités ne seront pas flush dans les UseCase

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Infrastructure/Adapter/EventDispatcher.php
> +class EventDispatcher implements EventDispatcherInterface
Ouais à la limite, un `__invoke(AbstractTermsEvent $event)`

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Infrastructure/Adapter/Logger.php
> +            $this->translator->trans(
dans une variable $message

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Infrastructure/Adapter/ResponseBuilder.php
> +        $this->defaultRefuseRoute = $parameterBag->get('rich_id_terms_module.default_redirection_routes.refusal');
Non, pas de get dans un constructor, on le fait que quand on a besoin

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Infrastructure/DependencyInjection/PrependDoctrineMigrationTrait.php
> +            'migrations_paths' => \array_merge(\array_pop($doctrineConfig)['migrations_paths'] ?? [], [
Tu peux utiliser des variables

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Infrastructure/FormType/TermsVersionFormType.php
> +    /* @phpstan-ignore-next-line */
Pourquoi ?

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/Infrastructure/Resources/views/_form-theme.html.twig
> +           {{ form_widget(form, {attr: attr|merge({class: (attr.class|default('') ~ ' terms-module-form-field-input')|trim})}) }}
Wah je comprends rien, tu peux faire `{% set ... %}`

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/UserInterface/Controller/AddTermsVersionRoute.php
> +        $this->adminRoles = $parameterBag->get('rich_id_terms_module.admin_roles');
Non, on fait le get en dehors du constructor

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/UserInterface/Controller/AddTermsVersionRoute.php
> +    /** @return array<string> */
@return string[]

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/UserInterface/Controller/EditAdminRoute.php
> +        $this->adminRoles = $parameterBag->get('rich_id_terms_module.admin_roles');
Toujours pas, cf au dessus

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/UserInterface/Controller/EditAdminRoute.php
> +    /** @return array<string> */
stirng[]

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/UserInterface/Controller/ListAdminRoute.php
> +        $this->adminRoles = $parameterBag->get('rich_id_terms_module.admin_roles');
Nop, tu pourras vérifier partout stp ?

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/UserInterface/Controller/ListAdminRoute.php
> +    /** @return array<string> */
Pareil, `string[]` est plus lisible, tu peux revérifier partout ?

2021-07-19 09:03 UTC, NicolasGuilloux commented on src/UserInterface/Controller/SignRoute.php
> +        if ($accepted === '') {
`return $accepted !== '' ? (bool) $accepted : null`

2021-07-19 09:15 UTC, mdevlamynck requested changes
Great work! Only a few small nitpicks :)

2021-07-19 09:15 UTC, mdevlamynck commented on src/UserInterface/Controller/AddTermsVersionRoute.php
> +        if (!$this->isGranted('MODULE_TERMS_ADMIN')) {
You can use the constant defined in the voter.

2021-07-19 09:15 UTC, mdevlamynck commented on src/Domain/EventListener/TermsSignedEventListener.php
> +final class TermsSignedEventListener
I prefer naming event listener after their behavior, `LogSignedTermsEventListener` or something like that, seems more appropriate.

2021-07-19 09:15 UTC, mdevlamynck commented on src/Domain/EventListener/TermsVersionEnabledEventListener.php
> +final class TermsVersionEnabledEventListener
Same thing, `SetTermsVersionPublicationMetadataEventListener` or something like that.

2021-07-19 09:15 UTC, mdevlamynck commented on src/Domain/EventListener/TermsVersionUpdatedEventListener.php
> +final class TermsVersionUpdatedEventListener
Same thing, `AutopublishFirstTermsVersionEventListener` or something like that.

2021-07-19 09:15 UTC, mdevlamynck commented on src/Domain/UseCase/HasSignLastTermsVersion.php
> +class HasSignLastTermsVersion
Small spelling mistake, should be has signed and has not signed.

2021-07-19 09:15 UTC, mdevlamynck commented on src/Domain/Entity/TermsVersion.php
> +        $entity->setTitle($termsVersion->getTitle()); /* @phpstan-ignore-line */
Add a comment to explain why this line is excluded from static analysis (and same remark for all the others).

Why is it excluded from static analysis? Is there a specific rule we want to ignore here (and can we ignore only that rule?) ?

2021-07-19 09:15 UTC, mdevlamynck commented on src/Infrastructure/Resources/translations/terms_module.en.yml
> +terms_module.sign.new_version: New version !
There is no space before an exclamation mark in english.

2021-07-19 09:18 UTC, hdumazeau commented on src/Domain/Model/DummyTermsGuardValidation.php
> +    public static function create(string $slug, string $type, string $identifier): self
Pour cela je ne trouve pas que ca ai du sens

2021-07-19 10:11 UTC, hdumazeau commented on src/Infrastructure/FormType/TermsVersionFormType.php
> +    /* @phpstan-ignore-next-line */
Phpstan fait chier avec les param

2021-07-19 14:21 UTC, NicolasGuilloux commented on composer.json
> +        "symfony/routing": "^4.0",
Symfony 5 siouplait

2021-07-19 14:36 UTC, NicolasGuilloux requested changes

2021-07-19 14:36 UTC, NicolasGuilloux commented on src/Domain/Factory/TermsVersionSignatureFactory.php
> +    public function sign(TermsVersion $version, TermsSubjectInterface $subject): TermsVersionSignature
__invoke

2021-07-19 14:36 UTC, NicolasGuilloux commented on src/Domain/Updater/TermsVersionUpdater.php
> +    public function update(TermsVersion $termsVersion, TermsEdition $termsEdition): TermsVersion
__invoke()

2021-07-19 14:36 UTC, NicolasGuilloux commented on src/Infrastructure/Resources/config/routing/routing.xml
> +
En trop

2021-07-20 07:58 UTC, NicolasGuilloux approved these changes

2021-07-20 08:05 UTC, mdevlamynck approved these changes

2021-07-20 08:07 UTC, merged